spring.application.name=skilltree
server.port=8080

spring.datasource.url=jdbc:postgresql://db:5432/skilltree
spring.datasource.username=postgres
spring.datasource.password=123465

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migrations

logging.level.root=INFO
logging.level.com.skilltree=DEBUG
logging.file.name=/SkillTree/backend/logs/skilltree.log
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger - %msg%n

spring.jpa.properties.hibernate.cache.use_second_level_cache=false
spring.jpa.properties.hibernate.cache.use_query_cache=false

jwt.secret=primitime_secret
jwt.expiration-ms=3600000

minio.endpoint=http://minio:9000
minio.access-key=minioadmin
minio.secret-key=minioadmin123
minio.bucket-name=skilltree-images